#!/bin/sh
###
#The values for the SSM parameters have been removed for security 
###

# Install cloudhsm client and JCE Provider downloaded in the base image, this is done here as a volume needs to first be attached.

echo "install"
id
mount 
ls *.rpm
pwd
#yum install -y ./cloudhsm-client-latest.el8.x86_64.rpm && yum install -y ./cloudhsm-client-jce-latest.el8.x86_64.rpm
echo "pre  bsd ls /opt/cloudhsm"
ls /opt/cloudhsm

echo "bsdtar /opt/cloudhsm"

cd  /
bsdtar -xvf /cloudhsm/hsmc.rpm
#bsdtar -xvf cloudhsm-client-jce-latest.el8.x86_64.rpm



# don't overwrite cloudhsm.conf on upgrade; there may be specific values that need to be retained


if [ ! -f /etc/security/limits.d/cloudhsm.conf ]; then
    echo -e "#\n#  DO NOT EDIT THIS FILE\n#" > /etc/security/limits.d/cloudhsm.conf
    echo "hsmuser  soft  nofile  3000" >> /etc/security/limits.d/cloudhsm.conf
    echo "hsmuser  hard  nofile  3000" >> /etc/security/limits.d/cloudhsm.conf
fi


CLOUDHSM_BASE=/opt/cloudhsm
CLOUDHSM_RUN=$CLOUDHSM_BASE/run
if [ $(stat -c %G $CLOUDHSM_BASE) = 'root' ]; then
  sudo chgrp hsmuser $CLOUDHSM_BASE
fi
if [ $(stat -c %U $CLOUDHSM_RUN) = 'root' -o $(stat -c %G $CLOUDHSM_RUN) = 'root' ]; then
  chown -R hsmuser:hsmuser $CLOUDHSM_RUN
fi

# Looking for the version of Python installed on the user's instance
EXPECTED_DIRS="/usr/local/bin /usr/bin" # Expected python locations
PYTHON_VERSIONS="python3 python2"

for DIR in ${EXPECTED_DIRS}; do
  for PYTHON_VERSION in ${PYTHON_VERSIONS}; do
    CANDIDATE_PATH=${DIR}/${PYTHON_VERSION}
    if [ -f "${CANDIDATE_PATH}" ] && [ -x "${CANDIDATE_PATH}" ]; then
      PYTHON_PATH=${CANDIDATE_PATH}
      break 2 # Stop at first occurance (highest precedence)
    fi
  done
done

if [ -z "${PYTHON_PATH}" ]; then
  echo "WARNING: Could not find a version of Python installed in /usr/local/bin or /usr/bin"
  echo "Please ensure Python is installed before running /opt/cloudhsm/bin/configure and /opt/cloudhsm/bin/client_info"
  exit 
fi

# Update shebang in configure file
sed -i "1s|.*|#!${PYTHON_PATH}|" ${CLOUDHSM_BASE}/bin/configure 
# Update shebang in client_info file
sed -i "1s|.*|#!${PYTHON_PATH}|" ${CLOUDHSM_BASE}/bin/client_info



# Cleanup - remove installation files
# rm -rf cloudhsm-client-latest.el8.x86_64.rpm && rm -rf cloudhsm-client-jce-latest.el8.x86_64.rpm

# Get HSM IP via awcli, credentials for AWS cli attached via a k8s service role.
echo "ls /opt/cloudhsm"
ls /opt/cloudhsm
vpc1=$(aws ec2 describe-vpcs --filters Name=tag:Name,Values=eksctl-ekshsm-cluster/VPC --query "Vpcs[].VpcId" | jq -r .[])
cid=$(aws cloudhsmv2 describe-clusters --filters vpcIds=$vpc1 --query "Clusters[].ClusterId" | jq -r .[])
HSM_IP=$(aws cloudhsmv2 describe-clusters --filters clusterIds=$cid --query "Clusters[].Hsms[].EniIp" | jq -r .[])
echo "vpc1=$vpc1"
echo "HSMIP=$HSM_IP"

echo "nmap check on $HSM_IP"
nmap ${HSM_IP} -Pn -p 2225
id
echo "# Configure CloudHSM Client"

cp /usr/lib/libncursesw.so.6 /usr/lib/libncurses.so.6
ls /usr/lib/libncur*

echo "ls /opt/cloudhsm/bin"
ls -l /opt/cloudhsm/bin
head /opt/cloudhsm/bin/configure
cd /opt/cloudhsm/bin
ls
pwd
echo "python"
ls /usr/bin/python3

/opt/cloudhsm/bin/configure -a "${HSM_IP}"

#echo "# Download CloudHSM CA" 
#aws --region=eu-west-2 ssm get-parameter --name "hsm-customerca-crt" --with-decryption --output text --query Parameter.Value --no-verify-ssl > /opt/cloudhsm/etc/customerCA.crt
#echo "ls /opt/cloudhsm/etc"
#ls /opt/cloudhsm/etc
#export HSM_USER="admin"
#export HSM_PASSWORD=$(aws --region=eu-west-2 ssm get-parameter --name "hsmpw" --with-decryption --output text --query Parameter.Value)
#echo "HSM_PASSWORD=$HSM_PASSWORD"
#echo "# Start CloudHSM as a daemon"
#/cloudhsm/startdaemon.sh

