#!/bin/sh
addgroup -g 1999 hsmuser
#/usr/bin/getent group hsmuser >/dev/null || /usr/sbin/groupadd -r hsmuser
#/usr/bin/getent passwd hsmuser >/dev/null || \
#    /usr/sbin/useradd -r -g hsmuser -d /opt/cloudhsm -s /sbin/nologin \
#                      -c "CloudHSM User" hsmuser

adduser -u 1999 -G hsmuser -h /opt/cloudhsm -D hsmuser

# don't overwrite cloudhsm.conf on upgrade; there may be specific values that need to be retained
apk add shadow

if [ ! -f /etc/security/limits.d/cloudhsm.conf ]; then
    echo -e "#\n#  DO NOT EDIT THIS FILE\n#" > /etc/security/limits.d/cloudhsm.conf
    echo "hsmuser  soft  nofile  3000" >> /etc/security/limits.d/cloudhsm.conf
    echo "hsmuser  hard  nofile  3000" >> /etc/security/limits.d/cloudhsm.conf
fi


CLOUDHSM_BASE=/opt/cloudhsm
CLOUDHSM_RUN=$CLOUDHSM_BASE/run
if [ $(stat -c %G $CLOUDHSM_BASE) = 'root' ]; then
  chgrp hsmuser $CLOUDHSM_BASE
fi
if [ $(stat -c %U $CLOUDHSM_RUN) = 'root' -o $(stat -c %G $CLOUDHSM_RUN) = 'root' ]; then
  chown -R hsmuser:hsmuser $CLOUDHSM_RUN
fi

# Looking for the version of Python installed on the user's instance
EXPECTED_DIRS="/usr/local/bin /usr/bin" # Expected python locations
PYTHON_VERSIONS="python3 python2"

for DIR in ${EXPECTED_DIRS}; do
  for PYTHON_VERSION in ${PYTHON_VERSIONS}; do
    CANDIDATE_PATH=${DIR}/${PYTHON_VERSION}
    if [ -f "${CANDIDATE_PATH}" ] && [ -x "${CANDIDATE_PATH}" ]; then
      PYTHON_PATH=${CANDIDATE_PATH}
      break 2 # Stop at first occurance (highest precedence)
    fi
  done
done

if [ -z "${PYTHON_PATH}" ]; then
  echo "WARNING: Could not find a version of Python installed in /usr/local/bin or /usr/bin"
  echo "Please ensure Python is installed before running /opt/cloudhsm/bin/configure and /opt/cloudhsm/bin/client_info"
  exit 
fi

# Update shebang in configure file
sed -i "1s|.*|#!${PYTHON_PATH}|" ${CLOUDHSM_BASE}/bin/configure 
# Update shebang in client_info file
sed -i "1s|.*|#!${PYTHON_PATH}|" ${CLOUDHSM_BASE}/bin/client_info

